name: Tweet

on:
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v2'
      - name: 'Run the tweet bot'
        uses: 'moonstar-x/twitter-today-is@github-actions'
        with:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          COORD_LAT: '-82.8628'
          COORD_LONG: '135.0000'